In [2]:
#Install the required library
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in /Users/huyennguyen/anaconda3/lib/python3.11/site-packages (2.9.13)
Requirement already satisfied: sqlalchemy in /Users/huyennguyen/anaconda3/lib/python3.11/site-packages (1.4.39)

In [ ]:
import pandas as pd
import numpy as np 
from sqlalchemy import create_engine

In [ ]:

# Replace with your actual PostgreSQL credentials
DB_USER     = "postgres"
DB_PASSWORD = "Ban..."
DB_HOST     = "localhost"        # or your server IP
DB_PORT     = "54.."            # default PostgreSQL port
DB_NAME     = "movie"

engine = create_engine(
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

# Test connection
with engine.connect() as conn:
    print("Successfully Connected to PostgreSQL!")

Successfully Connected to PostgreSQL!

In [ ]:
data = pd.read_excel('/Users/huyennguyen/Documents/MDD/SQL/alldatatables_cleaned.xlsx', 
                    sheet_name=['bridge_movie_genre', 'bridge_movie_cast',
                                'bridge_movie_studio', 'bridge_movie_director',
                                'bridge_movie_awards', 'bridge_movie_keyword'
                                'bridge_movie_expert', 'bridge_movie_user'], 
                    engine='openpyxl'
                    )

In [11]:
data = pd.read_excel('/Users/huyennguyen/Documents/MDD/SQL/alldatatables_cleaned.xlsx', 
                    sheet_name=['expert_review', 'user_review',
                                'bridge_movie_expert', 'bridge_movie_user'], 
                    engine='openpyxl'
                    )

In [12]:
expert_review = data['expert_review']
expert_review.head()

,id_expert_review,id_liwc,expert_name,review_date,idvscore,review_text,url
0,1,1,Andrew O'Hehir,NaT,100,Bronson owes a little or a lot to Kubrick s Cl...,https://www.metacritic.com/movie/bronson
1,2,2,A.O. Scott,NaT,90,Bronson invites you to admire its protagonist ...,https://www.metacritic.com/movie/bronson
2,3,3,Noel Murray,NaT,83,There are two Bronsons on display here: the im...,https://www.metacritic.com/movie/bronson
3,4,4,Joshua Rothkopf,NaT,80,Refn has somehow found his way to an authentic...,https://www.metacritic.com/movie/bronson
4,5,5,Bill Goodykoontz,NaT,80,"This is unhinged genius, an amazing piece of a...",https://www.metacritic.com/movie/bronson

In [13]:
user_review = data['user_review']
user_review.head()

,id_user_review,id_liwc,user_name,review_date,idvscore,thumbsup,thumbstot,review_text,url
0,1,233161,Longbottom94,2013-04-25,8,2,2,Many have dismissed this film for not explorin...,https://www.metacritic.com/movie/bronson
1,2,233162,MartinB,2009-10-13,9,0,1,Anyone who doesn t like this movie simply just...,https://www.metacritic.com/movie/bronson
2,3,233163,Jaakko,2012-07-19,10,1,1,Not sure what to think at this film at first. ...,https://www.metacritic.com/movie/bronson
3,4,233164,CapoR,2009-10-13,6,0,1,Nicely portrayed but it lacks the elements to ...,https://www.metacritic.com/movie/bronson
4,5,233165,OrwellB.,2009-10-10,8,0,0,Bronson is more than entertainment. It is art ...,https://www.metacritic.com/movie/bronson

In [14]:
bridge_movie_expert = data['bridge_movie_expert']
bridge_movie_expert.head()

   id_movie  id_expert_review
0         1               NaN
1         2           80698.0
2         2           80699.0
3         2           80700.0
4         2           80701.0

In [15]:
bridge_movie_user = data['bridge_movie_user']
bridge_movie_user.head()

   id_movie  id_user_review
0         1             NaN
1         2        125810.0
2         2        125811.0
3         2        125812.0
4         2        125813.0

In [31]:
bridge_movie_expert = pd.read_excel('alldatatables_cleaned.xlsx', sheet_name='bridge_movie_expert')
bridge_movie_expert.to_sql('bridge_movie_expert_review', engine, if_exists='append', index=False, chunksize=10000)
print("bridge_movie_expert table loaded!")

bridge_movie_expert table loaded!

In [32]:
bridge_movie_user = pd.read_excel('alldatatables_cleaned.xlsx', sheet_name='bridge_movie_user')
bridge_movie_user.to_sql('bridge_movie_user_review', engine, if_exists='append', index=False, chunksize=10000)
print("bridge_movie_user table loaded!")

bridge_movie_user table loaded!

In [27]:
expert_review = pd.read_excel('alldatatables_cleaned.xlsx', sheet_name='expert_review')
expert_review.to_sql('expert_review', engine, if_exists='append', index=False, chunksize=10000)
print("expert_review table loaded!")

expert_review table loaded!

In [26]:
user_review = pd.read_excel('alldatatables_cleaned.xlsx', sheet_name='user_review')
user_review.to_sql('user_review', engine, if_exists='append', index=False, chunksize=10000)
print("user_review table loaded!")

user_review table loaded!